#!/bin/bash

. "$(dirname "$0")"/../common/common_source
NAME=binutils
VERSION=${BINUTILS_VER}
FETCH_URL="http://ftp.gnu.org/gnu/binutils/$NAME-$VERSION.tar.xz"
TARFILE=$NAME-$VERSION.tar.xz

configure()
{
    cd "$TMP"/"$NAME"-"$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    CC=$LFS_TGT-gcc                 \
    AR=$LFS_TGT-ar                  \
    RANLIB=$LFS_TGT-ranlib          \
    ../configure     		    \
        --prefix=/tools             \
        --disable-nls               \
        --disable-werror            \
        --with-lib-path=/tools/lib  \
        --with-sysroot >>"$LOGFILE" 2>&1
}

post_build()
{
    {
    cd "$BUILD_PATH"
    make "$SILENT_MAKE" "$MAKE_JOBS" -C ld clean
    [ $? -ne 0 ] && return $?
    
    make "$SILENT_MAKE" "$MAKE_JOBS" -C ld LIB_PATH=/usr/lib:/lib
    [ $? -ne 0 ] && return $?
    
    cp -v ld/ld-new /tools/bin
    } >>"$LOGFILE" 2>&1
}

. "$(dirname "$0")"/../common/common_exec
