#!/bin/bash

. "$(dirname "$0")"/../common/common_source
NAME=tcl
VERSION=${TCL_VER}
FETCH_URL="https://downloads.sourceforge.net/tcl/$NAME$VERSION-src.tar.gz"
TARFILE=$NAME$VERSION-src.tar.gz

configure()
{
    cd "$TMP"/"${NAME}${VERSION}"
    mkdir build
    cd build

    BUILD_PATH=$(pwd)
    ../unix/configure --prefix=/tools >>"$LOGFILE" 2>&1
}

post_install()
{
    {
    chmod -v u+w /tools/lib/libtcl8.6.so
    make "$SILENT_MAKE" install-private-headers
    ln -sv tclsh8.6 /tools/bin/tclsh
    } >>"$LOGFILE" 2>&1
}

cleanup()
{
    default_cleanup "$TMP"/"${NAME}${VERSION}"
}

. "$(dirname "$0")"/../common/common_exec
