#!/bin/bash

. "$(dirname "$0")"/../common/common_source
NAME=tar
VERSION=${TAR_VER}
FETCH_URL="http://ftp.gnu.org/gnu/tar/$NAME-$VERSION.tar.xz"
TARFILE=$NAME-$VERSION.tar.xz

configure()
{
    default_configure "$TMP"/"$NAME"-"$VERSION"
}

. "$(dirname "$0")"/../common/common_exec
