#!/bin/bash

. "$(dirname "$0")"/../common/common_source
NAME=texinfo
VERSION=${TEXINFO_VER}
FETCH_URL="http://ftp.gnu.org/gnu/texinfo/$NAME-$VERSION.tar.xz"
TARFILE=$NAME-$VERSION.tar.xz

configure()
{
    default_configure "$TMP"/"$NAME"-"$VERSION"
}

. "$(dirname "$0")"/../common/common_exec
