#!/bin/bash

. "$(dirname "$0")"/../common/common_source
NAME=xz
VERSION=${XZ_VER}
FETCH_URL="https://tukaani.org/xz/$NAME-$VERSION.tar.xz"
TARFILE=$NAME-$VERSION.tar.xz

configure()
{
    default_configure "$TMP"/"$NAME"-"$VERSION"
}

. "$(dirname "$0")"/../common/common_exec
